#!/bin/bash

file=`ls gc_*.dat | sort -n -k 1.4`
n_file=`ls gc_*.dat | wc -w`

cat geometry.dat |  awk -F " " {'printf "%5g\t%g\n", $8, $9'} > tmp.dat

n=1

rm -f worldline.dat

for f in $file; do

gc_i=`echo ${f:3:-4} | sed 's/^0*//'`

namegc_f="`echo ${f:3:-4}`.png"
namegc_b="b`echo ${f:3:-4}`.png"
n_f=$(echo "scale=2;  100*$n/$n_file" |bc)

echo -ne "Processing file $f ($n_f%)..."\\r

paste tmp.dat $f > temp.dat

cat temp.dat | awk -v var="$gc_i" -F"\t" '$3 > -.2 && $3 <.2 {print $1 "\t" $2 "\t" var }' >> worldline.dat

gp_f="'temp.dat' u 1:2:3 w pm3d"
gp_b="'temp.dat' u 1:2:4 w pm3d"

gnuplot <<EOF
	set font 'Verdana,10'
	unset xlabel
	unset ylabel
	unset xtics
	unset ytics
	unset border
	unset colorbox
	set xrange [-3.1415:3.1415]
	set yrange [-1.57:1.57]
	set title "Stereographic projection"
	set xlabel "Angle with x axis"
	set ylabel "Angle with z axis"
	set term png crop size 1920,1080 font 'Verdana,14'
	set cbrange [-1:1]
	set palette defined (-1 "red", 1 "green")
	set out '$namegc_f'
	set nokey
	set view map
	set dgrid3d 100,100,3
	splot $gp_f
	set cbrange [0:1]
	set contour
	set out '$namegc_b'
	set palette defined (0 "red", 1 "green")
	splot $gp_b
EOF

n=$((n+1))

done

echo -e \\n"Building movie files..."

ffmpeg -framerate 10 -pattern_type glob -i "0*.png" 2d_field.mkv > /dev/null
ffmpeg -framerate 10 -pattern_type glob -i "b*.png" binary_2d_field.mkv > /dev/null

rm b0*.png
rm 0*.png
rm gc_*.dat
rm -f temp.dat
rm -f tmp.dat
