#!/bin/bash
rm -f temp*.dat
rm -f tmp*.dat
rm -f worldline*.dat

file=`ls gc_*.dat | sort -n -k 1.4`
n_file=`ls gc_*.dat | wc -w`

cat geometry.dat |  awk -F " " {'printf "%g\t%g\n", $8, $9'} > tmp.dat
cat geometry.dat |  awk -F " " {'printf "%g\t%g\t%g\n", $2, $3, $4'} > tmp1.dat

n=1

echo -e \\n"Building 3D images..."
xvfb-run --server-args="-screen 0 1024x768x24" python movie_3D.py 


echo -e \\n"Building 2D images..."
python movie_2D.py 

echo -e \\n"Building worldlines..."


for f in $file; do

gc_i=`echo ${f:3:-4} | sed 's/^0*//'`

namegc_f="`echo ${f:3:-4}`.png"
namegc_b="b`echo ${f:3:-4}`.png"
n_f=$(echo "scale=2;  100*$n/$n_file" |bc)

echo -ne "Processing file $f ($n_f%)..."\\r

paste tmp.dat $f > temp.dat
paste tmp1.dat $f > temp1.dat

cat temp.dat | awk -v var="$gc_i" -F"\t" '$3 > -.05 && $3 <.05 {print $1 "\t" $2 "\t" var }' >> worldline_2D.dat
cat temp1.dat | awk -v var="$gc_i" -F"\t" '$4 > -.05 && $4 <.05 {print $1 "\t" $2 "\t" $3 "\t" var }' >> worldline_3D.dat


n=$((n+1))

done

echo -e \\n"Building movies..."

ffmpeg -framerate 10 -pattern_type glob -i "0*.png" 2d_field.mkv > /dev/null 2>&1
ffmpeg -framerate 10 -pattern_type glob -i "t*.png" 3d_field.mkv > /dev/null 2>&1

rm 0*.png
rm gc_*.dat
rm t*.png
rm -f temp*.dat
rm -f tmp*.dat
