#!/bin/bash

file=`ls gc_*.dat | sort -n -k 1.4`
n_file=`ls gc_*.dat | wc -w`

cat geometry.dat |  awk -F " " {'printf "%g\t%g\n", $8, $9'} > tmp.dat

n=1

rm -f worldline.dat

for f in $file; do

gc_i=`echo ${f:3:-4} | sed 's/^0*//'`

namegc_f="`echo ${f:3:-4}`.png"
namegc_b="b`echo ${f:3:-4}`.png"
n_f=$(echo "scale=2;  100*$n/$n_file" |bc)

echo -ne "Processing file $f ($n_f%)..."\\r

paste tmp.dat $f > temp.dat

cat temp.dat | awk -v var="$gc_i" -F"\t" '$3 > -.2 && $3 <.2 {print $1 "\t" $2 "\t" var }' >> worldline.dat

python plot.py $f $namegc_f

n=$((n+1))

done

echo -e \\n"Building movie files..."

ffmpeg -framerate 10 -pattern_type glob -i "0*.png" 2d_field.mkv > /dev/null
#ffmpeg -framerate 10 -pattern_type glob -i "b*.png" binary_2d_field.mkv > /dev/null

rm -f b0*.png
rm 0*.png
#rm gc_*.dat
rm -f temp.dat
rm -f tmp.dat
