#!/bin/bash

rm -f 2d_field.mkv

file=`ls gc_*.dat | sort -n -k 1.4`
n_file=`ls gc_*.dat | wc -w`


cat geometry.dat |  awk -F " " {'printf "%g\n", $1'} > temp_n_phi.dat

n=1
lim=$1

for f in $file; do
	gc_i=`echo ${f:3:-4} | sed 's/^0*//'`
	namefig="`echo ${f:3:-4}`.png"
	n_f=$(echo "scale=2;  100*$n/$n_file" |bc)
	echo -ne "Processing file $f ($n_f %)..."\\r

	if [ ! -f $namefig ]; then
		paste temp_n_phi.dat $f > temp.dat
		gnuplot -e "f='temp.dat'; set term pngcairo size 1024,768; set output '$namefig'; plot f u 1:2"
	fi

	n=$((n+1))
done

echo -e \\n"Building movies..."

ffmpeg -framerate 24 -pattern_type glob -i "0*.png" 2d_field.mkv > /dev/null 2>&1

rm -f temp.dat
#rm 0*.png
