#!/bin/bash

# Total number of steps in the concentration, going from 0 to 1 (both values included, so the total number is acutally c0steps+1). 
n_c0=10

# Coupling counter (from 0 to g_i with n_g steps)
n_g=25
g_i=2.5

# Number of runs per phase diagram point
rpp=3

rm -fR testconf
mkdir -p testconf

# Re-initialising counters
c0_c=0
g_c=0
rpp_c=0
n=0
fn=0

while [ $g_c -le $n_g ];
	do
	g=$(echo "scale=3; $g_c/$n_g*$g_i" |bc)
	while [  $c0_c -le $n_c0 ]; 
	do
		while [  $rpp_c -lt $rpp ]; 
		do
		c0=$(echo "scale=3; $c0_c/$n_c0" |bc)
		let n=n+1
		echo -ne "Processing $g $c0 $rpp_c (found $fn out of $n )"\\r
		DIR=temp_${g}_${c0}_${rpp_c}
		if [ -d "$DIR" ]; then
			if [ -e "$DIR/last.dat" ]; then
				let fn=fn+1
				cp $DIR/last.dat testconf/conf_${g}_${c0}_${rpp_c}_last.dat
				cat $DIR/final.dat | awk -v var1="$g" -v var2="$c0"  -F"\t" '{print var1,"\t", var2,"\t", $2,"\t", $3,"\t", $4,"\t", $5,"\t", $6,"\t", $7,"\t", $8,"\t",$9}'  >> testconf/final.dat
			else
				break
			fi
		else
			break
		fi

		let rpp_c=rpp_c+1
		
		done 
	rpp_c=0
	let c0_c=c0_c+1 
	done
	c0_c=0
let g_c=g_c+1
done
echo " "
echo "Found $fn (of $n) directories  with useful data"
