#!/bin/bash
rm -f temp*.dat
rm -f tmp*.dat
rm -f worldline*.dat
rm -f 3d_field.mkv

dir=$1
row=$2

file=`ls $dir/conf_$(echo $row)_0_*_0_last.dat | sort -n -k 1.4`
n_file=`ls $(echo $dir/conf_$(echo $row)_0_*_0_last.dat) | wc -l`

n=1

if [ "$#" -gt 1 ]; then
	for f in $file; do

		namegc_f="`echo ${f:-4}`.png"
		if [ $n -lt 10 ]; then
			namen_f="0$n.png"
		else
			namen_f="$n.png"
		fi
		n_f=$(echo "scale=2;  100*$n/$n_file" |bc)
	
		echo -ne "Processing file $f ($n_f%)..."\\r

		sleep 4
	
		xvfb-run --server-args="-screen 0 1024x768x24" python plot_3D.py $f $namen_f .035
		#python plot_3D.py $f $namen_f .035

		n=$((n+1))

	done
fi
