#!/bin/bash

g_in=$1
g_fin=$2

n=$3
ncount=0

xcount=0
xmax=$4

convert -size 1920x1080 xc:white blank.png

while [ $g_in -le $g_fin ];  do

	while [ $ncount -le $n ];  do

		while [ $xcount -le $xmax ];  do

			if [ -e ../finalconfigurations/t_${g_in}_${xcount}_${ncount}.png ]; then
				cp ../finalconfigurations/t_${g_in}_${xcount}_${ncount}.png .

			else
				cp blank.png t_${g_in}_${xcount}_${ncount}.png
			fi
			let xcount+=1

		done
		
		xcount=0

		tot=`ls t_${g_in}_*_${ncount}.png | wc -w`

		montage $(ls -1 t_${g_in}_*_${ncount}.png | sort -t _ -V)  -geometry +2+2 -tile 1x${tot} tcolumn_${g_in}_${ncount}.jpg

		convert tcolumn_${g_in}_${ncount}.jpg -resize 400 smalltcolumn_${g_in}_${ncount}.jpg

		rm tcolumn_${g_in}_${ncount}.jpg

		rm t_${g_in}_*_${ncount}.png

		let ncount+=1

	done

	ncount=0

	let g_in+=1

done

ncount=0

while [ $ncount -le $n ];  do
	tot=`ls smalltcolumn_*_${ncount}.png | wc -w`
	montage $(ls -1 smalltcolumn_*_${ncount}.jpg | sort -t _ -V)  -geometry +2+2 -tile ${tot}x1 tfinal_${ncount}.jpg
	let ncount+=1
done

rm blank.png
rm smalltcolumn*
